# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubCrawl.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubCrawl(object):
    """
    This class contains code generated from the QtDesigner. The .ui file is still contained in the ui directory.
    """
    def setupUi(self, SubCrawl):
        SubCrawl.setObjectName("SubCrawl")
        SubCrawl.resize(1280, 1024)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(SubCrawl.sizePolicy().hasHeightForWidth())
        SubCrawl.setSizePolicy(sizePolicy)
        SubCrawl.setMinimumSize(QtCore.QSize(1280, 1024))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(9)
        SubCrawl.setFont(font)
        SubCrawl.setLayoutDirection(QtCore.Qt.LeftToRight)
        SubCrawl.setDocumentMode(False)
        SubCrawl.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(SubCrawl)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ScanLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ScanLabel_2.setMinimumSize(QtCore.QSize(290, 110))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.ScanLabel_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(46)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ScanLabel_2.setFont(font)
        self.ScanLabel_2.setObjectName("ScanLabel_2")
        self.horizontalLayout.addWidget(self.ScanLabel_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_4.setFont(font)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.ScanLabel = QtWidgets.QLabel(self.centralwidget)
        self.ScanLabel.setMinimumSize(QtCore.QSize(250, 110))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 80, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.ScanLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.ScanLabel.setFont(font)
        self.ScanLabel.setIndent(10)
        self.ScanLabel.setObjectName("ScanLabel")
        self.horizontalLayout.addWidget(self.ScanLabel)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BrowseButton.sizePolicy().hasHeightForWidth())
        self.BrowseButton.setSizePolicy(sizePolicy)
        self.BrowseButton.setMinimumSize(QtCore.QSize(150, 40))
        self.BrowseButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.BrowseButton.setFont(font)
        self.BrowseButton.setObjectName("BrowseButton")
        self.gridLayout_3.addWidget(self.BrowseButton, 0, 0, 1, 1)
        self.StartScanButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartScanButton.sizePolicy().hasHeightForWidth())
        self.StartScanButton.setSizePolicy(sizePolicy)
        self.StartScanButton.setMinimumSize(QtCore.QSize(160, 40))
        self.StartScanButton.setMaximumSize(QtCore.QSize(200, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.StartScanButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.StartScanButton.setFont(font)
        self.StartScanButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.StartScanButton.setObjectName("StartScanButton")
        self.gridLayout_3.addWidget(self.StartScanButton, 1, 2, 1, 1)
        self.SelectedFolderDisplay = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectedFolderDisplay.sizePolicy().hasHeightForWidth())
        self.SelectedFolderDisplay.setSizePolicy(sizePolicy)
        self.SelectedFolderDisplay.setMinimumSize(QtCore.QSize(700, 40))
        self.SelectedFolderDisplay.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Amiri")
        font.setPointSize(12)
        self.SelectedFolderDisplay.setFont(font)
        self.SelectedFolderDisplay.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.SelectedFolderDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SelectedFolderDisplay.setLineWidth(2)
        self.SelectedFolderDisplay.setIndent(10)
        self.SelectedFolderDisplay.setObjectName("SelectedFolderDisplay")
        self.gridLayout_3.addWidget(self.SelectedFolderDisplay, 0, 1, 1, 2)
        self.CancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.CancelButton.setEnabled(False)
        self.CancelButton.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout_3.addWidget(self.CancelButton, 1, 1, 1, 1)
        self.gridLayout_3.setRowMinimumHeight(0, 1)
        self.gridLayout_3.setRowMinimumHeight(1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ScanProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ScanProgressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Amiri")
        font.setPointSize(8)
        self.ScanProgressBar.setFont(font)
        self.ScanProgressBar.setProperty("value", 0)
        self.ScanProgressBar.setTextVisible(False)
        self.ScanProgressBar.setInvertedAppearance(False)
        self.ScanProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ScanProgressBar.setObjectName("ScanProgressBar")
        self.verticalLayout.addWidget(self.ScanProgressBar)
        self.line = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.ScannedItems = QtWidgets.QTableWidget(self.centralwidget)
        self.ScannedItems.setEnabled(True)
        self.ScannedItems.setMinimumSize(QtCore.QSize(1256, 443))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ScannedItems.setFont(font)
        self.ScannedItems.setFrameShape(QtWidgets.QFrame.Box)
        self.ScannedItems.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ScannedItems.setLineWidth(1)
        self.ScannedItems.setMidLineWidth(1)
        self.ScannedItems.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ScannedItems.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ScannedItems.setTabKeyNavigation(False)
        self.ScannedItems.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.ScannedItems.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ScannedItems.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.ScannedItems.setShowGrid(True)
        self.ScannedItems.setGridStyle(QtCore.Qt.SolidLine)
        self.ScannedItems.setRowCount(0)
        self.ScannedItems.setColumnCount(6)
        self.ScannedItems.setObjectName("ScannedItems")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ScannedItems.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ScannedItems.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ScannedItems.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ScannedItems.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ScannedItems.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ScannedItems.setHorizontalHeaderItem(5, item)
        self.ScannedItems.horizontalHeader().setVisible(True)
        self.ScannedItems.horizontalHeader().setCascadingSectionResizes(True)
        self.ScannedItems.horizontalHeader().setDefaultSectionSize(208)
        self.ScannedItems.horizontalHeader().setMinimumSectionSize(208)
        self.ScannedItems.horizontalHeader().setSortIndicatorShown(True)
        self.ScannedItems.horizontalHeader().setStretchLastSection(True)
        self.ScannedItems.verticalHeader().setVisible(False)
        self.ScannedItems.verticalHeader().setMinimumSectionSize(37)
        self.verticalLayout.addWidget(self.ScannedItems)
        self.verticalLayout.setStretch(0, 1)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 0, 1, 4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.ViewButtonFrame = QtWidgets.QFrame(self.centralwidget)
        self.ViewButtonFrame.setObjectName("ViewButtonFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.ViewButtonFrame)
        self.gridLayout.setContentsMargins(5, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.ShowAllRadio = QtWidgets.QRadioButton(self.ViewButtonFrame)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.ShowAllRadio.setFont(font)
        self.ShowAllRadio.setChecked(True)
        self.ShowAllRadio.setObjectName("ShowAllRadio")
        self.gridLayout.addWidget(self.ShowAllRadio, 0, 0, 1, 1)
        self.ShowSubsRadio = QtWidgets.QRadioButton(self.ViewButtonFrame)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.ShowSubsRadio.setFont(font)
        self.ShowSubsRadio.setObjectName("ShowSubsRadio")
        self.gridLayout.addWidget(self.ShowSubsRadio, 1, 0, 1, 1)
        self.ShowNoSubsRadio = QtWidgets.QRadioButton(self.ViewButtonFrame)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.ShowNoSubsRadio.setFont(font)
        self.ShowNoSubsRadio.setObjectName("ShowNoSubsRadio")
        self.gridLayout.addWidget(self.ShowNoSubsRadio, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.ViewButtonFrame)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 0, 0, 4, 1)
        self.ClearDBButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearDBButton.setEnabled(True)
        self.ClearDBButton.setMinimumSize(QtCore.QSize(150, 30))
        self.ClearDBButton.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.ClearDBButton.setFont(font)
        self.ClearDBButton.setObjectName("ClearDBButton")
        self.gridLayout_4.addWidget(self.ClearDBButton, 0, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_4.addWidget(self.line_6, 1, 1, 1, 2)
        self.ConfirmSelectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmSelectionButton.setEnabled(False)
        self.ConfirmSelectionButton.setMinimumSize(QtCore.QSize(150, 30))
        self.ConfirmSelectionButton.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.ConfirmSelectionButton.setFont(font)
        self.ConfirmSelectionButton.setCheckable(False)
        self.ConfirmSelectionButton.setChecked(False)
        self.ConfirmSelectionButton.setAutoDefault(False)
        self.ConfirmSelectionButton.setDefault(False)
        self.ConfirmSelectionButton.setFlat(False)
        self.ConfirmSelectionButton.setObjectName("ConfirmSelectionButton")
        self.gridLayout_4.addWidget(self.ConfirmSelectionButton, 3, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SelectAllRadio = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.SelectAllRadio.setFont(font)
        self.SelectAllRadio.setChecked(False)
        self.SelectAllRadio.setObjectName("SelectAllRadio")
        self.verticalLayout_4.addWidget(self.SelectAllRadio)
        self.SelectedRowsCount = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.SelectedRowsCount.setFont(font)
        self.SelectedRowsCount.setText("")
        self.SelectedRowsCount.setObjectName("SelectedRowsCount")
        self.verticalLayout_4.addWidget(self.SelectedRowsCount)
        self.gridLayout_4.addWidget(self.frame_2, 2, 1, 1, 2)
        self.RemoveEntryButton = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveEntryButton.setEnabled(False)
        self.RemoveEntryButton.setMinimumSize(QtCore.QSize(150, 30))
        self.RemoveEntryButton.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.RemoveEntryButton.setFont(font)
        self.RemoveEntryButton.setObjectName("RemoveEntryButton")
        self.gridLayout_4.addWidget(self.RemoveEntryButton, 0, 2, 1, 1)
        self.CancelSelectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.CancelSelectionButton.setEnabled(False)
        self.CancelSelectionButton.setMinimumSize(QtCore.QSize(150, 30))
        self.CancelSelectionButton.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.CancelSelectionButton.setFont(font)
        self.CancelSelectionButton.setObjectName("CancelSelectionButton")
        self.gridLayout_4.addWidget(self.CancelSelectionButton, 3, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 2)
        self.OpenSubtitlesCheck = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.OpenSubtitlesCheck.setFont(font)
        self.OpenSubtitlesCheck.setChecked(True)
        self.OpenSubtitlesCheck.setObjectName("OpenSubtitlesCheck")
        self.gridLayout_2.addWidget(self.OpenSubtitlesCheck, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 3, 1, 1)
        self.LanguageComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.LanguageComboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.LanguageComboBox.setFont(font)
        self.LanguageComboBox.setFrame(True)
        self.LanguageComboBox.setObjectName("LanguageComboBox")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.gridLayout_2.addWidget(self.LanguageComboBox, 2, 1, 1, 1)
        self.LanguageLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.LanguageLabel.setFont(font)
        self.LanguageLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LanguageLabel.setLineWidth(1)
        self.LanguageLabel.setMidLineWidth(1)
        self.LanguageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LanguageLabel.setObjectName("LanguageLabel")
        self.gridLayout_2.addWidget(self.LanguageLabel, 3, 1, 1, 1)
        self.SubsDbCheck = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(10)
        self.SubsDbCheck.setFont(font)
        self.SubsDbCheck.setChecked(True)
        self.SubsDbCheck.setObjectName("SubsDbCheck")
        self.gridLayout_2.addWidget(self.SubsDbCheck, 3, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 1, 0, 5, 1)
        self.DownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadButton.setEnabled(False)
        self.DownloadButton.setMaximumSize(QtCore.QSize(350, 40))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(12)
        self.DownloadButton.setFont(font)
        self.DownloadButton.setCheckable(False)
        self.DownloadButton.setChecked(False)
        self.DownloadButton.setAutoDefault(False)
        self.DownloadButton.setDefault(False)
        self.DownloadButton.setFlat(False)
        self.DownloadButton.setObjectName("DownloadButton")
        self.gridLayout_2.addWidget(self.DownloadButton, 4, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 1, 1, 3)
        self.gridLayout_2.setRowStretch(0, 3)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 2, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PromptLabel = QtWidgets.QLabel(self.centralwidget)
        self.PromptLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Museo Sans For Dell")
        font.setPointSize(14)
        self.PromptLabel.setFont(font)
        self.PromptLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.PromptLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PromptLabel.setLineWidth(2)
        self.PromptLabel.setIndent(5)
        self.PromptLabel.setObjectName("PromptLabel")
        self.verticalLayout_3.addWidget(self.PromptLabel)
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.ProgressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.ProgressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.ProgressBar.setTextVisible(False)
        self.ProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ProgressBar.setObjectName("ProgressBar")
        self.verticalLayout_3.addWidget(self.ProgressBar)
        self.verticalLayout_3.setStretch(0, 1)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 3, 0, 1, 4)
        self.gridLayout_5.setColumnStretch(3, 2)
        self.gridLayout_5.setRowStretch(1, 1)
        SubCrawl.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SubCrawl)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menubar.setObjectName("menubar")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        SubCrawl.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SubCrawl)
        self.statusbar.setObjectName("statusbar")
        SubCrawl.setStatusBar(self.statusbar)
        self.actionScanning = QtWidgets.QAction(SubCrawl)
        self.actionScanning.setObjectName("actionScanning")
        self.actionSubtitles = QtWidgets.QAction(SubCrawl)
        self.actionSubtitles.setObjectName("actionSubtitles")
        self.actionAbout = QtWidgets.QAction(SubCrawl)
        self.actionAbout.setObjectName("actionAbout")
        self.actionContribute = QtWidgets.QAction(SubCrawl)
        self.actionContribute.setObjectName("actionContribute")
        self.menuPreferences.addAction(self.actionScanning)
        self.menuPreferences.addAction(self.actionSubtitles)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionContribute)
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(SubCrawl)
        QtCore.QMetaObject.connectSlotsByName(SubCrawl)

    def retranslateUi(self, SubCrawl):
        _translate = QtCore.QCoreApplication.translate
        SubCrawl.setWindowTitle(_translate("SubCrawl", "SubCrawl"))
        self.ScanLabel_2.setText(_translate("SubCrawl", "SubCrawl"))
        self.ScanLabel.setText(_translate("SubCrawl", "Scan folders\n"
"for movies"))
        self.BrowseButton.setText(_translate("SubCrawl", "Browse"))
        self.StartScanButton.setText(_translate("SubCrawl", "Start scan"))
        self.SelectedFolderDisplay.setText(_translate("SubCrawl", "..."))
        self.CancelButton.setText(_translate("SubCrawl", "Cancel"))
        self.ScannedItems.setSortingEnabled(True)
        item = self.ScannedItems.horizontalHeaderItem(0)
        item.setText(_translate("SubCrawl", "IMDb ID"))
        item = self.ScannedItems.horizontalHeaderItem(1)
        item.setText(_translate("SubCrawl", "Title"))
        item = self.ScannedItems.horizontalHeaderItem(2)
        item.setText(_translate("SubCrawl", "IMDb rating"))
        item = self.ScannedItems.horizontalHeaderItem(3)
        item.setText(_translate("SubCrawl", "Year"))
        item = self.ScannedItems.horizontalHeaderItem(4)
        item.setText(_translate("SubCrawl", "File location"))
        item = self.ScannedItems.horizontalHeaderItem(5)
        item.setText(_translate("SubCrawl", "Subtitles"))
        self.label_3.setText(_translate("SubCrawl", "Table view:"))
        self.ShowAllRadio.setText(_translate("SubCrawl", "Show all movies"))
        self.ShowSubsRadio.setText(_translate("SubCrawl", "Show movies with subtitles"))
        self.ShowNoSubsRadio.setText(_translate("SubCrawl", "Show movies without subtitles"))
        self.ClearDBButton.setText(_translate("SubCrawl", "Clear database"))
        self.ConfirmSelectionButton.setText(_translate("SubCrawl", "Confirm selection"))
        self.SelectAllRadio.setText(_translate("SubCrawl", "Select all"))
        self.RemoveEntryButton.setText(_translate("SubCrawl", "Remove entry"))
        self.CancelSelectionButton.setText(_translate("SubCrawl", "Cancel selection"))
        self.label.setText(_translate("SubCrawl", "Select subtitle language:"))
        self.OpenSubtitlesCheck.setText(_translate("SubCrawl", "OpenSubtitles"))
        self.label_2.setText(_translate("SubCrawl", "Select from where to download subtitles:"))
        self.LanguageComboBox.setItemText(0, _translate("SubCrawl", "Albanian"))
        self.LanguageComboBox.setItemText(1, _translate("SubCrawl", "Afghan"))
        self.LanguageComboBox.setItemText(2, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(3, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(4, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(5, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(6, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(7, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(8, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(9, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(10, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(11, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(12, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(13, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(14, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(15, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(16, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(17, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(18, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(19, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(20, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(21, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(22, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(23, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(24, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(25, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(26, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(27, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(28, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(29, _translate("SubCrawl", "New Item"))
        self.LanguageComboBox.setItemText(30, _translate("SubCrawl", "New Item"))
        self.LanguageLabel.setText(_translate("SubCrawl", "Language: Albanian"))
        self.SubsDbCheck.setText(_translate("SubCrawl", "SubdsDb"))
        self.DownloadButton.setText(_translate("SubCrawl", "Download"))
        self.PromptLabel.setText(_translate("SubCrawl", "Ready to download!"))
        self.menuPreferences.setTitle(_translate("SubCrawl", "Preferences"))
        self.menuAbout.setTitle(_translate("SubCrawl", "About"))
        self.actionScanning.setText(_translate("SubCrawl", "Scanning"))
        self.actionSubtitles.setText(_translate("SubCrawl", "Subtitles"))
        self.actionAbout.setText(_translate("SubCrawl", "About"))
        self.actionContribute.setText(_translate("SubCrawl", "Contribute"))

